# Generated by Django 3.0.6 on 2020-12-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('img1', models.ImageField(upload_to='yogbookingapp/media/images')),
                ('img2', models.ImageField(upload_to='yogbookingapp/media/images')),
                ('text', models.CharField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=20)),
                ('no_of_students', models.IntegerField(default=0)),
                ('date_of_event', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='yogbookingapp/media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('fathers_name', models.CharField(default='', max_length=20)),
                ('aadhar', models.IntegerField(default='0')),
                ('address', models.CharField(default='', max_length=20)),
                ('experiance', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('resume', models.FileField(upload_to='yogbookingapp/media/pdf')),
                ('profile', models.ImageField(upload_to='yogbookingapp/media/images')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('price', models.IntegerField(default='0')),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='yogbookingapp/media/images')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('fathers_name', models.CharField(default='', max_length=20)),
                ('aadhar', models.IntegerField(default='0')),
                ('address', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=50)),
                ('profile', models.ImageField(upload_to='yogbookingapp/media/images')),
                ('proffession', models.CharField(default='', max_length=20)),
                ('gender', models.CharField(default=0, max_length=5)),
            ],
        ),
    ]
