# Generated by Django 3.0.7 on 2021-01-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0003_auto_20210105_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img1',
            field=models.ImageField(upload_to='yogbookingapp/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img2',
            field=models.ImageField(upload_to='yogbookingapp/images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='profile',
            field=models.ImageField(upload_to='yogbookingapp/images'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='resume',
            field=models.FileField(upload_to='yogbookingapp/pdf'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='yogbookingapp/images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(upload_to='yogbookingapp/images'),
        ),
    ]
