# Generated by Django 3.0.7 on 2021-01-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0004_auto_20210105_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='id',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
