# Generated by Django 3.0.7 on 2021-01-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0005_auto_20210105_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcommingevent',
            fields=[
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='yogbookingapp/images')),
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
    ]
