# Generated by Django 3.0.6 on 2021-01-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0006_upcommingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='dob',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='instructor',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='instructor',
            name='mobile',
            field=models.IntegerField(default='', max_length=12),
        ),
    ]
