# Generated by Django 3.0.6 on 2021-01-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0007_auto_20210107_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='dob',
        ),
        migrations.AddField(
            model_name='instructor',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
