# Generated by Django 3.0.6 on 2021-01-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0008_auto_20210107_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='date',
            new_name='dob',
        ),
    ]
