# Generated by Django 3.0.6 on 2021-01-07 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogbookingapp', '0010_remove_instructor_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcommingevent',
            name='date',
        ),
    ]
